# Generated by Django 4.2.11 on 2024-04-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_contestboard_rating_remove_contestinfo_oj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestplayer',
            options={'verbose_name': '比赛选手', 'verbose_name_plural': '比赛选手'},
        ),
    ]
