# Generated by Django 4.2.11 on 2024-04-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contestplayer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestplayer',
            options={},
        ),
    ]
