# Generated by Django 4.2.11 on 2024-04-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='score',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(default=1, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userloginrecord',
            name='ip',
            field=models.CharField(default='unknow', max_length=50, null=True, verbose_name='登陆IP'),
        ),
        migrations.AlterField(
            model_name='userloginrecord',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='登陆时间'),
        ),
        migrations.AlterField(
            model_name='userloginrecord',
            name='msg',
            field=models.TextField(null=True, verbose_name='其他信息'),
        ),
        migrations.AlterField(
            model_name='userloginrecord',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='ac',
            field=models.IntegerField(default=0, verbose_name='AC数'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='acpro',
            field=models.TextField(default='', null=True, verbose_name='AC题号'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='des',
            field=models.CharField(max_length=50, null=True, verbose_name='用户简介'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='submit',
            field=models.IntegerField(default=0, verbose_name='提交数'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
    ]
