# Generated by Django 4.2.11 on 2024-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userstatus_rating_remove_userstatus_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='language',
            field=models.CharField(default='C++|C|Python3|Python2|Swift5.1|Java', max_length=500, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='oj_name',
            field=models.CharField(default='NOJ', max_length=100, verbose_name='OJ名称'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='open_code',
            field=models.BooleanField(default=True, verbose_name='代码查看'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='open_oi',
            field=models.BooleanField(default=True, verbose_name='OI赛制'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='open_register',
            field=models.BooleanField(default=True, verbose_name='开放注册'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='open_testcase',
            field=models.BooleanField(default=True, verbose_name='显示用例'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='open_visitor',
            field=models.BooleanField(default=True, verbose_name='游客访问'),
        ),
    ]
