# Generated by Django 4.2.11 on 2024-03-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ProblemInfo',
            name='oj',
        ),
    ]
