# Generated by Django 4.2.11 on 2024-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_remove_problemmeta_oj'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
