# Generated by Django 4.2.11 on 2024-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(default='admin', max_length=50, verbose_name='出题人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='desc',
            field=models.TextField(verbose_name='题目描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(default='', null=True, verbose_name='提示'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='in_desc',
            field=models.TextField(verbose_name='输入描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='in_sample',
            field=models.TextField(verbose_name='输入样例'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='mem_limit',
            field=models.IntegerField(verbose_name='内存限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='out_desc',
            field=models.TextField(verbose_name='输出描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='out_sample',
            field=models.TextField(verbose_name='输出样例'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='题目ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='priv',
            field=models.IntegerField(default=1, verbose_name='题目权限'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(verbose_name='时间限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=500, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.IntegerField(default=1, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='ac',
            field=models.IntegerField(default=0, verbose_name='AC数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='ce',
            field=models.IntegerField(default=0, verbose_name='CE数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='level',
            field=models.IntegerField(default=1, verbose_name='题目难度'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='mle',
            field=models.IntegerField(default=0, verbose_name='MLE数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='pe',
            field=models.IntegerField(default=0, verbose_name='PE数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='pid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='题目ID'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='priv',
            field=models.IntegerField(default=1, verbose_name='题目权限'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='rte',
            field=models.IntegerField(default=0, verbose_name='RTE数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='score',
            field=models.IntegerField(default=100, verbose_name='题目分数'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='se',
            field=models.IntegerField(default=0, verbose_name='SE数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='submission',
            field=models.IntegerField(default=0, verbose_name='提交数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='tag',
            field=models.TextField(null=True, verbose_name='题目标签'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='title',
            field=models.CharField(max_length=500, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='tle',
            field=models.IntegerField(default=0, verbose_name='TLE数量'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='wa',
            field=models.IntegerField(default=0, verbose_name='WA数量'),
        ),
        migrations.AlterField(
            model_name='problemtag',
            name='num',
            field=models.IntegerField(verbose_name='使用数量'),
        ),
        migrations.AlterField(
            model_name='problemtag',
            name='tagname',
            field=models.CharField(max_length=50, unique=True, verbose_name='标签内容'),
        ),
    ]
