# Generated by Django 4.2.11 on 2024-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionresult',
            name='judger',
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='casedata',
            field=models.CharField(max_length=500, verbose_name='测试用例数据'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='memory',
            field=models.IntegerField(default=0, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='outputdata',
            field=models.CharField(default='', max_length=500, verbose_name='正确输出'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='problem',
            field=models.CharField(max_length=50, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='result',
            field=models.CharField(default='System Error', max_length=500, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='submit_id',
            field=models.IntegerField(verbose_name='提交ID'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='testcase',
            field=models.CharField(default='unknow', max_length=500, verbose_name='测试用例名称'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='time',
            field=models.IntegerField(default=0, verbose_name='用时'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='useroutput',
            field=models.CharField(default='', max_length=500, verbose_name='用户输出'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='code',
            field=models.TextField(max_length=200000, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='contest',
            field=models.IntegerField(verbose_name='所属比赛'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='contest_problem',
            field=models.IntegerField(default=-1, verbose_name='比赛内部题号'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='error_case',
            field=models.CharField(default='0', max_length=50, verbose_name='错误用例'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='ip',
            field=models.CharField(default='无法获取ip', max_length=50, verbose_name='提交IP'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='language',
            field=models.CharField(max_length=50, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='length',
            field=models.IntegerField(verbose_name='代码长度'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='memory',
            field=models.IntegerField(verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='message',
            field=models.TextField(verbose_name='其他错误消息'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='problem',
            field=models.CharField(max_length=50, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='problem_title',
            field=models.CharField(default='', max_length=100, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='result',
            field=models.IntegerField(verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='submit_time',
            field=models.DateTimeField(verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='time',
            field=models.IntegerField(verbose_name='用时'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='user',
            field=models.CharField(max_length=50, verbose_name='提交用户'),
        ),
    ]
